import express from 'express';

import { BadRequest, InternalServerError } from '../errorHandler.js';
import { CustomerContacts } from '../models.js';
import { HttpStatus } from './index.js';

const customerContactRouter = express.Router({ mergeParams: true });

const checkCustomerId = (req, _res, next) => {
  const { customerId } = req.params;
  if (!customerId) {
    throw new InternalServerError();
  }
  next();
};

// Check that customer ID is present in the request parameters matched by the parent router.
customerContactRouter.use(checkCustomerId);

/**
 *  MB-DONE: Let's assume application uses relation database (like PostgreSQL). The database has following tables:
 *  - customer (customer_id SERIAL PRIMARY KEY, name TEXT NOT NULL, country TEXT, is_active BOOLEAN)
 *  - contact (contact_id SERIAL PRIMARY KEY, first_name TEXT NOT NULL, last_name TEXT NOT NULL)
 *  - customer_contact (customer_id REFERENCES customer, contact_id REFERENCES contact, PRIMARY KEY(customer_id, contact_id))
 */

/**
 * MB-DONE: Write a SQL query in comment how to fetch a contacts of customer using provided database pseudo schema
 *
 * SELECT contact.contact_id, contact.first_name, contact.last_name
 * FROM contact
 * JOIN customer_contact AS cc
 *   ON contact.contact_id = cc.contact_id
 * WHERE cc.customer_id = <<SANITIZED_CUSTOMER_ID>>;
 */

// MB-DONE: Create route for fetching contacts of a customer `/api/customers/:customerId/contacts`
customerContactRouter.get('/', async (req, res) => {
  const { customerId } = req.params;
  return res.send(await CustomerContacts.getAll(customerId));
});

/**
 * MB-DONE: Write a SQL query in comment how to upsert a contacts to a customer using provided database pseudo schema
 *
 * -- Using transaction to prevent creating unlinked contact if second insert fails.
 * -- This might happen for example due to incorrect `customer_id` violating foreign key constraint on `customer_contact`.
 * BEGIN;
 * WITH created_contact_id AS (
 *   -- Assuming autogenerated `contact_id` for new contacts
 *   INSERT INTO contact (first_name, last_name)
 *     VALUES (<<SANITIZED_FIRST_NAME>>, <<SANITIZED_LAST_NAME>>)
 *     -- Assuming UNIQUE(first_name, last_name) constraint on the `contact` table based on the "upsert" instruction in the task specification
 *     ON_CONFLICT (first_name, last_name)
 *     DO UPDATE SET
 *       contact_id = contact.contact_id
 *     -- Using PostgreSQL syntax
 *     RETURNING contact_id
 * )
 * INSERT INTO customer_contact (customer_id, contact_id)
 *   SELECT <<SANITIZED_CUSTOMER_ID>>, contact_id FROM created_contact_id;
 * COMMIT;
 */
// MB-DONE: Create route for adding contact to a customer `/api/customers/:customerId/contacts`
customerContactRouter.post('/', async (req, res) => {
  const { customerId } = req.params;
  const { contactId } = req.body;
  if (!contactId) {
    throw new BadRequest(
      `Required field 'contactId' missing from request body`
    );
  }

  const customerContact = await CustomerContacts.add(customerId, contactId);
  if (!customerContact) {
    throw new InternalServerError(
      `Failed to add contact ${contactId} to customer ${customerId}`
    );
  }

  return res.status(HttpStatus.CREATED).send(customerContact);
});

/**
 * MB-DONE: Write a SQL query in comment how to delete a contact of customer using provided database pseudo schema
 *
 * -- Assumptions made before:
 * -- * DB is PostgreSQL
 * -- * `contact` has unique naming constraint (=> m2m relation between `customer` and `contact`)
 *
 * -- Transaction just in case :)
 * BEGIN;
 * -- Delete link from relation table
 * DELETE FROM customer_contact
 * WHERE customer_id = <<SANITIZED_CUSTOMER_ID>> AND contact_id = <<SANITIZED_CONTACT_ID>>;
 *
 * -- Delete contact entry if no foreign key references to it in `customer_contact`
 * DELETE FROM contact
 * WHERE contact_id = <<SANITIZED_CONTACT_ID>>
 *   AND NOT EXISTS (
 *       SELECT 1 FROM customer_contact
 *       WHERE contact_id = <<SANITIZED_CONTACT_ID>>
 *   );
 * COMMIT;
 */
// MB-DONE:s Create route for deleting contact of customer `/api/customers/:customerId/contacts/:contactId`
customerContactRouter.delete('/:contactId', async (req, res) => {
  const { customerId, contactId } = req.params;
  await CustomerContacts.delete(customerId, contactId);
  res.sendStatus(HttpStatus.NO_CONTENT);
});

export default customerContactRouter;
